stages:
    - test
default:
    image: ubuntu:23.04
    before_script:
        - export DEBIAN_FRONTEND=noninteractive 
        # Install utils
        - apt-get update > /dev/null
        - apt-get install -qqy curl wget tree xxd gettext-base cpio > /dev/null
        # Install go
        - apt-get install -qqy golang-1.19
        - export PATH=/usr/lib/go-1.19/bin:$PATH
        # Install task
        - GOBIN=/usr/local/bin go install github.com/go-task/task/v3/cmd/task@v3.29.1
        - export PATH=$PATH:/usr/local/bin
        # Install QEMU
        - apt-get -qqy install qemu-system-x86 > /dev/null
        # Install Toolchain dependencies
        - task deps:install > /dev/null
        # Install test-only tools
        - apt-get install -qqy --no-install-recommends python3-pip
        # Override externally-managed-environment check.
        - pip install --break-system-packages --user virt-firmware

        - task --version
        - go version

# Doesn't run actual tests, but tests for obvious failures in the
# scripts used for running tests on real hardware.
Test tools:
    stage: test
    script:
      - ./contrib/testing/build-ospkg.sh
      - ./contrib/testing/build-stprov.sh
      - ./contrib/testing/build-stboot.sh
