# Taskfile is not supported by upstream task yet.
# https://github.com/system-transparency/task/tree/dev
version: '4'

output: 'interleaved'

vars:
  # override go environment
  go_env: 'export GO111MODULE="off"; export GOPATH="${PWD}/cache/go"; '

dotenv:
  - .config

includes:
  go: ./go.yml
  deps: ./dependencies.yml

tasks:

  debug:
    cmds:
      - '{{.go_env}} echo hello world: ${GOPATH}'

  default:
    deps: [image]

  config:
    desc: Generate default configuration
    cmds:
      - ./scripts/config.sh -o .config
    sources:
      - contrib/default.config
    generates:
      - .config

  toolchain:
    desc: Build/Update toolchain
    deps:
      - go:all

######## stboot-installation ########

  image:
    desc: Build target installation option
    cmds:
      - make image
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""

  data_partition:
    cmds:
      - 'mkdir -p out/stboot-installation'
      - './stboot-installation/common/build_data_filesystem.sh'
    sources:
      - out/os-packages
    generates:
      - out/stboot-installation/data_partition.ext4
    label: >
      data partition
      (
      ST_DATA_PARTITION_EXTRA_SPACE={{.ST_DATA_PARTITION_EXTRA_SPACE}}'
      ST_BOOT_MODE={{.ST_BOOT_MODE}}'
      )
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""

######## keygen ########

  keygen:
    desc: Generate all example keys
    deps:
      - keygen-sign
      - keygen-cpu

  keygen-sign:
    desc: Generate example sign keys
    cmds:
      - './scripts/make_signing_keys.sh -o out/keys/signing_keys/'
    generates:
      - out/keys/signing_keys/*
    deps:
      - go:stmanager

  keygen-cpu:
    desc: Generate cpu ssh keys for debugging
    cmds:
      - './scripts/make_cpu_keys.sh -o out/keys/cpu_keys/'
    generates:
      - out/keys/cpu_keys/*

######## LinuxBoot kernel ########

  kernel:
    desc: Build LinuxBoot kernel
    cmds:
      - make kernel -j `nproc`

######## cleanup ########

  clean:
    desc: Remove all build artifacts
    cmds:
      - rm -rf out

  clean-keys:
    desc: Remove all keys
    cmds:
      - rm -rf out/keys

  clean-os:
    desc: Remove os-packages
    cmds:
      - rm -rf out/os-packages

  clean-all:
    desc: Remove all build artifacts, cache and config file
    deps: [clean]
    cmds:
      - rm -rf cache
      - rm -f .config
