version: '3'

vars:
  # Build Targets
  ISO: out/stboot.iso
  UKI: out/stboot.uki
  UKI_SIGNED: out/stboot.uki.signed
  # Build Artifacts
  STBOOT_LINUX_KERNEL: out/artifacts/stboot.vmlinuz
  STBOOT_INITRAMFS: out/artifacts/stboot.cpio.gz
  TRUST_POLICY: out/artifacts/trust_policy.json
  HOST_CONFIG: out/artifacts/host_config.json


includes:
  demo: ./tasks/demo.yml
  deps: ./tasks/deps.yml
  go: ./tasks/go.yml
  linux: ./tasks/linux.yml
  initramfs: ./tasks/initramfs.yml
  qemu: ./tasks/qemu.yml
  

output: 'prefixed'

tasks:

  default:
    cmds:
      - task -l
    interactive: true

  fetch:
    desc: Fetch dependencies which require network access
    deps:
      - go:all
      - linux:fetch

  toolchain:
    desc: Build toolchain
    deps:
      - go:update

  fullrun:
    cmds:
      - task: demo:ubuntu-prebuilt
      - task: demo:ospkg
      - task: iso
      - task: qemu:iso

  iso:
    desc: Build stboot iso image
    deps:
      - task: hostconfig-network
      - task: linux:kernel-prebuilt # Use pre compiled kernel. Take linux:kernel for compiling.
      - task: initramfs:incl-hostconfig
    sources:
      - "{{.STBOOT_LINUX_KERNEL}}"
      - "{{.STBOOT_INITRAMFS}}"
    generates:
      - "{{.ISO}}"
    cmds:
      - "{{.GOBIN}}/stmgr uki create -format iso -out '{{.ISO}}' -kernel={{.STBOOT_LINUX_KERNEL}} -initramfs={{.STBOOT_INITRAMFS}}" -cmdline="console=tty0 console=ttyS0,115200n8"
    run: once

  iso-no-hostcfg:
    desc: Build stboot iso image
    deps:
      - task: hostconfig-network
      - task: linux:kernel-prebuilt # Use pre compiled kernel. Take linux:kernel for compiling.
      - task: initramfs:standard
    sources:
      - "{{.STBOOT_LINUX_KERNEL}}"
      - "{{.STBOOT_INITRAMFS}}"
    generates:
      - "{{.ISO}}"
    cmds:
      - "{{.GOBIN}}/stmgr uki create -format iso -out '{{.ISO}}' -kernel={{.STBOOT_LINUX_KERNEL}} -initramfs={{.STBOOT_INITRAMFS}}"
    run: once

  iso-ospkg:
    desc: Build stboot iso image including an OS package inside the initramfs
    deps:
      - task: hostconfig-initramfs
      - task: linux:kernel-prebuilt # Use pre compiled kernel. Take linux:kernel for compiling.
      - task: initramfs:incl-ospkg
    sources:
      - "{{.STBOOT_LINUX_KERNEL}}"
      - "{{.STBOOT_INITRAMFS}}"
    generates:
      - "{{.ISO}}"
    cmds:
      - "{{.GOBIN}}/stmgr uki create -format iso -out '{{.ISO}}' -kernel={{.STBOOT_LINUX_KERNEL}} -initramfs={{.STBOOT_INITRAMFS}}"
    run: once

  iso-provision:
    desc: Build stboot iso image including NO hostconfig but an provision OS package inside the initramfs
    deps:
      - task: linux:kernel-prebuilt # Use pre compiled kernel. Take linux:kernel for compiling.
      - task: initramfs:provision
    sources:
      - "{{.STBOOT_LINUX_KERNEL}}"
      - "{{.STBOOT_INITRAMFS}}"
    generates:
      - "{{.ISO}}"
    cmds:
      - "{{.GOBIN}}/stmgr uki create -format iso -out '{{.ISO}}' -kernel={{.STBOOT_LINUX_KERNEL}} -initramfs={{.STBOOT_INITRAMFS}}"
    run: once

  uki:
    desc: Build stboot UKI
    deps:
      - task: go:stmgr
      - task: go:sthsm
      - task: linux:kernel-prebuilt # Use pre compiled kernel. Change to linux:kernel for compiling your own.
      - task: initramfs:standard
    sources:
      - "{{.STBOOT_LINUX_KERNEL}}"
      - "{{.STBOOT_INITRAMFS}}"
    generates:
      - "{{.UKI}}"
    cmds:
      - "{{.GOBIN}}/stmgr uki create -format uki -out '{{.UKI}}' -sbat ./contrib/sbat.csv -kernel={{.STBOOT_LINUX_KERNEL}} -initramfs={{.STBOOT_INITRAMFS}}"
    run: once


  netboot-img:       # FIXME: Signing the UKI probably belongs in demo
    desc: Sign stboot UKI using an already provisioned YubiHSM
    deps:
      - task: uki
    sources:
      - "{{.UKI}}"
    generates:
      - "{{.UKI_SIGNED}}"
    cmds:
      - "{{.GOBIN}}/mgmt --auth-key-label='Glasklar Admin Key' --password='keins' sign efi --in='{{.UKI}}' --id='0xe37b' --out='{{.UKI_SIGNED}}'"
    run: once


  trustpolicy:
    internal: yes
    deps:
      - task: go:stmgr
    generates:
      - "{{.TRUST_POLICY}}"
    cmds:
      - cmd: mkdir -p $(dirname {{.TRUST_POLICY}})
        silent: true
      - cmd: |-
          {{.GOBIN}}/stmgr trustpolicy check '{{.JSON}}' > {{.TRUST_POLICY}}
    vars:
      JSON: "{{.JSON}}"

  trustpolicy-network:
    desc: Generate trust_policy.json with arbitray data but ospkg_fetch_method set to "network"
    cmds:
      - task: trustpolicy
        vars:
          JSON: |-
            { 
              "ospkg_signature_threshold": 2,
              "ospkg_fetch_method": "network"
            }

  trustpolicy-initramfs:
    desc: Generate trust_policy.json with arbitray data but ospkg_fetch_method set to "initramfs"
    cmds:
      - task: trustpolicy
        vars:
          JSON: |-
            { 
              "ospkg_signature_threshold": 2,
              "ospkg_fetch_method": "initramfs"
            }

  hostconfig-network:
    internal: yes
    deps:
      - task: go:stmgr
    generates:
      - "{{.HOST_CONFIG}}"
    cmds:
      - cmd: mkdir -p $(dirname {{.HOST_CONFIG}})
        silent: true
      - cmd: |-
          {{.GOBIN}}/stmgr hostconfig check '{{.JSON}}' > {{.HOST_CONFIG}}
    vars:
      JSON: |-
          { 
            "network_mode":"dhcp",
            "host_ip":null,
            "gateway":null,
            "dns":null,
            "network_interfaces":null,
            "ospkg_pointer": "http://10.0.2.2:8080/os-pkg-example-ubuntu20.json",
            "identity":null,
            "authentication":null,
            "timestamp":null,
            "bonding_mode": "",
            "bond_name": ""
          }
    
  hostconfig-initramfs:
    internal: yes
    deps:
      - task: go:stmgr
    generates:
      - "{{.HOST_CONFIG}}"
    cmds:
      - cmd: mkdir -p $(dirname {{.HOST_CONFIG}})
        silent: true
      - cmd: |-
          {{.GOBIN}}/stmgr hostconfig check '{{.JSON}}' > {{.HOST_CONFIG}}
    vars:
      JSON: |-
          { 
            "network_mode":"dhcp",
            "host_ip":null,
            "gateway":null,
            "dns":null,
            "network_interfaces":null,
            "ospkg_pointer": "ospkg.json",
            "identity":null,
            "authentication":null,
            "timestamp":null,
            "bonding_mode": "",
            "bond_name": ""
          }

######## cleanup ########

  clean:
    desc: Remove all build artifacts
    cmds:
      - "rm -rf out"

  clean-toolchain:
    desc: Remove all go tools
    deps:
      - go:clean

  clean-all:
    desc: Remove all build artifacts, cache and config file
    deps:
      - clean
      - go:clean
    cmds:
      - "rm -rf cache"
      - "rm -rf .task"
