version: '3'

vars:
  # Config file
  CONFIG: st.config
  # Build Targets
  ISO: out/stboot.iso
  PROVISO: out/prov.iso
  # Build Artifacts
  STBOOT_LINUX_IMAGE: out/artifacts/stboot.vmlinuz
  STBOOT_INITRAMFS: out/artifacts/stboot.cpio.gz
  TRUST_POLICY: out/artifacts/trust_policy.json
  # task helper script
  CONFIG_HELPER: "CONFIG={{.CONFIG}} ./.task_config.sh"


dotenv:
  - "{{.CONFIG}}"

includes:
  demo: ./tasks/demo.yml
  deps: ./tasks/deps.yml
  go: ./tasks/go.yml
  linux: ./tasks/linux.yml
  stboot: ./tasks/stboot.yml
  qemu: ./tasks/qemu.yml
  proviso: ./tasks/provision.yml

output: 'prefixed'

tasks:

  default:
    cmds:
      - task -l
    interactive: true

  fetch:
    desc: Fetch dependencies which require network access
    deps:
      - check-config
      - go:all
      - linux:fetch

  config:
    desc: Generate default configuration
    sources:
      - "{{.DEFAULT_CONFIG}}"
    generates:
      - "{{.CONFIG}}"
    cmds:
      - cmd: >-
             if [ -f {{.CONFIG}} ]; then
             echo Moving old config to {{.CONFIG}}.old;
             mv {{.CONFIG}} {{.CONFIG}}.old;
             fi
        silent: true
      - cp {{.DEFAULT_CONFIG}} {{.CONFIG}}
    vars:
      DEFAULT_CONFIG: contrib/default.config

  toolchain:
    desc: Build toolchain
    deps:
      - go:update

  iso:
    desc: Build stboot iso image
    deps:
      - check-config
      - task: linux:kernel
        vars:
          IMAGE: "{{.STBOOT_LINUX_IMAGE}}"
          INITRAMFS: "{{.STBOOT_INITRAMFS}}"
          INITRAMFS_TARGET: "stboot:initramfs-standard"
    sources:
      - "{{.STBOOT_LINUX_IMAGE}}"
    generates:
      - "{{.ISO}}"
    cmds:
      - rm -rf {{.ISO_FAT}}
      - mkdir -p {{.ISO_DIR}}
      # ugly size calculation before call to mkfs.vfat needed
      - >- 
            tot_size=$(du -cb {{.STBOOT_LINUX_IMAGE}} | tail -1 | awk '{print $1}');
            size_vfat=$((tot_size + (1<<20)));
            vfat_blocks=$((size_vfat >> 10));
            vfat_blocks=$(((($vfat_blocks+32)&~31)));
            mkfs.vfat -C -n STBOOTISO {{.ISO_FAT}} $vfat_blocks
      - mmd -i {{.ISO_FAT}} ::/EFI
      - mmd -i {{.ISO_FAT}} ::/EFI/BOOT
      - mcopy -i {{.ISO_FAT}} {{.STBOOT_LINUX_IMAGE}} ::/EFI/BOOT/BOOTX64.EFI
      - xorriso -as mkisofs -R -f -e stboot.fat -no-emul-boot -o {{.ISO}} {{.ISO_DIR}}
    run: once
    vars:
      ISO_DIR: cache/iso
      ISO_FAT: ./{{.ISO_DIR}}/stboot.fat

  iso-ospkg:
    desc: Build stboot iso image including an OS package inside the initramfs
    deps:
      - check-config
      - task: linux:kernel
        vars:
          IMAGE: "{{.STBOOT_LINUX_IMAGE}}"
          INITRAMFS: "{{.STBOOT_INITRAMFS}}"
          INITRAMFS_TARGET: "stboot:initramfs-incl-ospkg"
    sources:
      - "{{.STBOOT_LINUX_IMAGE}}"
    generates:
      - "{{.ISO}}"
    cmds:
      - rm -rf {{.ISO_FAT}}
      - mkdir -p {{.ISO_DIR}}
      # ugly size calculation before call to mkfs.vfat needed
      - >- 
            tot_size=$(du -cb {{.STBOOT_LINUX_IMAGE}} | tail -1 | awk '{print $1}');
            size_vfat=$((tot_size + (1<<20)));
            vfat_blocks=$((size_vfat >> 10));
            vfat_blocks=$(((($vfat_blocks+32)&~31)));
            mkfs.vfat -C -n STBOOTISO {{.ISO_FAT}} $vfat_blocks
      - mmd -i {{.ISO_FAT}} ::/EFI
      - mmd -i {{.ISO_FAT}} ::/EFI/BOOT
      - mcopy -i {{.ISO_FAT}} {{.STBOOT_LINUX_IMAGE}} ::/EFI/BOOT/BOOTX64.EFI
      - xorriso -as mkisofs -R -f -e stboot.fat -no-emul-boot -o {{.ISO}} {{.ISO_DIR}}
    run: once
    vars:
      ISO_DIR: cache/iso
      ISO_FAT: ./{{.ISO_DIR}}/stboot.fat


  trust-policy:
    deps:
      - check-config
    generates:
      - "{{.TRUST_POLICY}}"
    cmds:
      - cmd: mkdir -p $(dirname {{.TRUST_POLICY}})
        silent: true
      - |-
        cat > "{{.TRUST_POLICY}}" <<EOL
        {
          "ospkg_signature_threshold": {{.ST_NUM_SIGNATURES}},
          "ospkg_fetch_method": "{{.ST_FETCH_METHOD}}"
        }
        EOL
    status:
      - "{{.CONFIG_HELPER}} trust-policy {{.DEPS}}"
      - "[ -f {{.TRUST_POLICY}} ]"
    run: once
    vars:
      DEPS: >-
        ST_NUM_SIGNATURES
        ST_FETCH_METHOD

  trust-policy-fetch-method-initramfs:
    deps:
      - check-config
    generates:
      - "{{.TRUST_POLICY}}"
    cmds:
      - cmd: mkdir -p $(dirname {{.TRUST_POLICY}})
        silent: true
      - |-
        cat > "{{.TRUST_POLICY}}" <<EOL
        {
          "ospkg_signature_threshold": {{.ST_NUM_SIGNATURES}},
          "ospkg_fetch_method": "initramfs"
        }
        EOL
    status:
      - "{{.CONFIG_HELPER}} trust-policy {{.DEPS}}"
      - "[ -f {{.TRUST_POLICY}} ]"
    run: once
    vars:
      DEPS: >-
        ST_NUM_SIGNATURES
        ST_FETCH_METHOD


######## checks ########

  # TODO: add config file validation
  check-config:
    preconditions:
      - sh: '[ -f "{{.CONFIG}}" ]'
        msg: |-
          [ERROR] File "{{.CONFIG}}" missing
          Please provide a configuration file or run "task config"
    run: once

######## cleanup ########

  clean:
    desc: Remove all build artifacts
    cmds:
      - "rm -rf out"

  clean-toolchain:
    desc: Remove all go tools
    deps:
      - go:clean

  clean-all:
    desc: Remove all build artifacts, cache and config file
    deps:
      - clean
      - go:clean
    cmds:
      - "rm -rf cache"
      - "rm -rf .task"
      - "rm -f {{.CONFIG}}"


######## somehow outdated, maybe remove it ########
# it builds the stmgr provision hostconfig tool into
# an own iso/initramfs. This GUI tool was never actually used.
# It prompts for hostconfig input and writes it to qemu efivar.

  proviso:
    desc: Build provisioning iso image
    deps:
      - check-config
      - task: linux:kernel
        vars:
          IMAGE: "{{.PROVISIONING_LINUX_IMAGE}}"
          INITRAMFS: "{{.PROVISIONING_INITRAMFS}}"
          INITRAMFS_TARGET: "proviso:provisioning-initramfs"
    sources:
      - ./{{.PROVISIONING_LINUX_IMAGE}}
    generates:
      - ./{{.PROVISO}}
    cmds:
      - rm -rf {{.PROVISO_FAT}}
      - mkdir -p {{.ISO_DIR}}
      - mkfs.vfat -C -n PROVISO {{.PROVISO_FAT}} {{.BLOCKS}}
      - mmd -i {{.PROVISO_FAT}} ::/EFI
      - mmd -i {{.PROVISO_FAT}} ::/EFI/BOOT
      - mcopy -i {{.PROVISO_FAT}} {{.PROVISIONING_LINUX_IMAGE}} ::/EFI/BOOT/BOOTX64.EFI
      - xorriso -as mkisofs -R -f -e provision.fat -no-emul-boot -o {{.PROVISO}} {{.ISO_DIR}}
    vars:
      ISO_DIR: cache/proviso
      PROVISO_FAT: ./{{.ISO_DIR}}/provision.fat
      # TODO: Calculate size
      BLOCKS:
        sh: echo $((1<<16))