version: '3'

vars:
  GO_ENV: 'GO111MODULE="off" GOPATH="${PWD}/cache/go"'
  # target files:
  CONFIG: .config
  DEFAULT_CONFIG: contrib/default.config
  DATA_PART: out/stboot-installation/data_partition.ext4
  MBR_IMAGE: out/stboot-installation/mbr-bootloader/stboot_mbr_installation.img
  EFI_IMAGE: out/stboot-installation/efi-application/stboot_efi_installation.img
  MBR_BOOT_PART: out/stboot-installation/mbr-bootloader/boot_partition.vfat
  EFI_BOOT_PART: out/stboot-installation/efi-application/boot_partition.vfat
  KERNEL_FILE: out/stboot-installation/linuxboot.vmlinuz
  INITRAMFS_FILE: out/stboot-installation/initramfs-linuxboot.cpio.gz
  HOST_CONFIG: out/stboot-installation/host_configuration.json
  SECURITY_CONFIG: out/stboot-installation/security_configuration.json
  SYSLINUX_BIN: cache/syslinux/syslinux-6.03/bios/mtools/syslinux
  SYSLINUX_CONFIG: out/stboot-installation/mbr-bootloader/syslinux.cfg
  # target directorys:
  SIGNKEYS_DIR: out/keys/signing_keys/
  CPUKEYS_DIR: out/keys/cpu_keys/
  OS_DIR: out/os-packages/
  # scripts:
  CONFIG_SCRIPT: ./scripts/config.sh
  MBR_IMAGE_SCRIPT: ./stboot-installation/mbr-bootloader/build_image.sh
  EFI_IMAGE_SCRIPT: ./stboot-installation/efi-application/build_image.sh
  MBR_BOOT_PART_SCRIPT: ./stboot-installation/mbr-bootloader/build_boot_filesystem.sh
  EFI_BOOT_PART_SCRIPT: ./stboot-installation/efi-application/build_boot_filesystem.sh
  DATA_PART_SCRIPT: ./stboot-installation/common/build_data_filesystem.sh
  INITRAMFS_SCRIPT: ./stboot-installation/common/build_initramfs.sh
  HOST_CONFIG_SCRIPT: ./stboot-installation/common/build_host_config.sh
  SECURITY_CONFIG_SCRIPT: ./stboot-installation/common/build_security_config.sh
  SYSLINUX_BIN_SCRIPT: ./stboot-installation/mbr-bootloader/fetch_syslinux.sh
  SYSLINUX_CONFIG_SCRIPT: ./stboot-installation/mbr-bootloader/build_syslinux_config.sh
  KEYGEN_SIGN_SCRIPT: ./scripts/make_signing_keys.sh
  KEYGEN_CPU_SCRIPT: ./scripts/make_cpu_keys.sh
  # make modules
  LINUX_MAKE: modules/linux.mk
  # task helper script
  CONFIG_HELPER: ./.task_config.sh

dotenv:
  - .config

includes:
  go: ./go.yml
  deps: ./deps.yml

output: 'prefixed'

### custom Anchors

preconditions:
  <<: &check-config
    sh: test -f "{{.CONFIG}}"
    msg: "Configuration ({{.CONFIG}}) file missing\nPlease provide a config file or run \"task config\""
  <<: &check-key
    sh: test -f "{{.ST_SIGNING_ROOT}}"
    msg: "root certificate ({{.ST_SIGNING_ROOT}}) missing\nPlease provide a certificate or run \"task keygen-sign\""

###

tasks:

  default:
    deps:
      - image

  config:
    desc: Generate default configuration
    sources:
      - "{{.DEFAULT_CONFIG}}"
    generates:
      - "{{.CONFIG}}"
    cmds:
      - "{{.CONFIG_SCRIPT}} -o {{.CONFIG}}"

  # XXX: Does not update toolchain binary!
  # TODO: Force toolchain rebuild for this target only
  # current workaround: task clean-toolchain toolchain
  toolchain:
    desc: Build toolchain
    deps:
      - go:all

######## stboot-installation ########

  image:
    desc: Build target installation option
    # TODO: make target installation option optional
    deps: [image-mbr]
    preconditions:
      - *check-config

  image-mbr:
    desc: Build MBR bootloader installation option
    deps:
      - mbr-boot-part
      - data-part
    sources:
      - "{{.MBR_BOOT_PART}}"
      - "{{.DATA_PART}}"
    generates:
      - "{{.MBR_IMAGE}}"
    cmds:
      - "{{.MBR_IMAGE_SCRIPT}} -o {{.MBR_IMAGE}}"
    status:
      - "{{.CONFIG_HELPER}} image-mbr {{.MBR_IMAGE_SCRIPT}}"
    preconditions:
      - *check-config

  image-efi:
    desc: Build EFI application installation option
    deps:
      - efi-boot-part
      - data-part
    sources:
      - "{{.EFI_BOOT_PART}}"
      - "{{.DATA_PART}}"
    generates:
      - "{{.EFI_IMAGE}}"
    cmds:
      - "{{.EFI_IMAGE_SCRIPT}} -o {{.EFI_IMAGE}}"
    status:
      - "{{.CONFIG_HELPER}} image-efi {{.EFI_IMAGE_SCRIPT}}"
    preconditions:
      - *check-config

  mbr-boot-part:
    deps:
      - kernel
      - host-config
      - syslinux
      - syslinux-config
    sources:
      - "{{.INITRAMFS_FILE}}"
      - "{{.HOST_CONFIG}}"
      - "{{.SYSLINUX_BIN}}"
      - "{{.SYSLINUX_CONFIG}}"
    generates:
      - "{{.MBR_BOOT_PART}}"
    cmds:
      - "{{.MBR_BOOT_PART_SCRIPT}} -o {{.MBR_BOOT_PART}}"
    status:
      - "{{.CONFIG_HELPER}} mbr-boot-part {{.MBR_BOOT_PART_SCRIPT}}"
    preconditions:
      - *check-config

  efi-boot-part:
    deps:
      - kernel
      - host-config
    sources:
      - "{{.INITRAMFS_FILE}}"
      - "{{.HOST_CONFIG}}"
    generates:
      - "{{.EFI_BOOT_PART}}"
    cmds:
      - "{{.EFI_BOOT_PART_SCRIPT}} -o {{.EFI_BOOT_PART}}"
    status:
      - "{{.CONFIG_HELPER}} efi-boot-part {{.EFI_BOOT_PART_SCRIPT}}"
    preconditions:
      - *check-config

  data-part:
    sources:
      - "{{.OS_DIR}}/**"
    generates:
      - "{{.DATA_PART}}"
    cmds:
      - "{{.DATA_PART_SCRIPT}} -o {{.DATA_PART}}"
    status:
      - "{{.CONFIG_HELPER}} data-part {{.DATA_PART_SCRIPT}}"
    preconditions:
      - *check-config

  host-config:
    generates:
      - "{{.HOST_CONFIG}}"
    cmds:
      - "{{.HOST_CONFIG_SCRIPT}} -o {{.HOST_CONFIG}}"
    status:
      - "{{.CONFIG_HELPER}} host-config {{.HOST_CONFIG_SCRIPT}}"
    preconditions:
      - *check-config

  security-config:
    generates:
      - "{{.SECURITY_CONFIG}}"
    cmds:
      - "{{.SECURITY_CONFIG_SCRIPT}} -o {{.SECURITY_CONFIG}}"
    status:
      - "{{.CONFIG_HELPER}} security-config {{.SECURITY_CONFIG_SCRIPT}}"
    preconditions:
      - *check-config

  syslinux:
    generates:
      - "{{.SYSLINUX_BIN}}"
    cmds:
      - "{{.SYSLINUX_BIN_SCRIPT}}"
        # TODO: integrate into the the script above
      - cp cache/syslinux/syslinux-6.03/efi32/efi/syslinux.efi out/stboot-installation/mbr-bootloader/BOOTIA32.EFI
      - cp cache/syslinux/syslinux-6.03/efi64/efi/syslinux.efi out/stboot-installation/mbr-bootloader/BOOTX64.EFI
    status:
      - test -x "{{.SYSLINUX_BIN}}"

  syslinux-config:
    generates:
      - "{{.SYSLINUX_CONFIG}}"
    cmds:
      - "{{.SYSLINUX_CONFIG_SCRIPT}} -o {{.SYSLINUX_CONFIG}}"
    status:
      - test -f "{{.SYSLINUX_CONFIG}}"

######## keygen ########

  keygen:
    desc: Generate all example keys
    deps:
      - keygen-sign
      - keygen-cpu

  keygen-sign:
    desc: Generate example sign keys
    deps:
      - go:stmanager
    generates:
      - "{{.SIGNKEYS_DIR}}/*"
    cmds:
      - "{{.GO_ENV}} {{.KEYGEN_SIGN_SCRIPT}} -o {{.SIGNKEYS_DIR}}"
    status:
      - "{{.CONFIG_HELPER}} keygen-sign {{.KEYGEN_SIGN_SCRIPT}}"

  keygen-cpu:
    desc: Generate cpu ssh keys for debugging
    generates:
      - "{{.CPUKEYS_DIR}}/*"
    cmds:
      - "{{.KEYGEN_CPU_SCRIPT}} -o {{.CPUKEYS_DIR}}"
    status:
      - "{{.CONFIG_HELPER}} keygen-cpu {{.KEYGEN_CPU_SCRIPT}}"
    preconditions:
      - *check-config

######## LinuxBoot kernel ########

  kernel:
    desc: Build LinuxBoot kernel
    deps:
      - initramfs
    sources:
      - "{{.INITRAMFS_FILE}}"
    generates:
      - "{{.KERNEL_FILE}}"
    cmds:
      - make -f "{{.LINUX_MAKE}}" OUT=out/stboot-installation CACHE=cache
    status:
      - "{{.CONFIG_HELPER}} kernel {{.LINUX_MAKE}}"
    preconditions:
      - *check-config

  initramfs:
    deps:
      - go:u-root
      - security-config
    sources:
      - "{{.SECURITY_CONFIG}}"
    generates:
      - "{{.INITRAMFS_FILE}}"
    cmds:
      - "{{.INITRAMFS_SCRIPT}} -o {{.INITRAMFS_FILE}}"
    status:
      - "{{.CONFIG_HELPER}} initramfs {{.INITRAMFS_SCRIPT}}"
    preconditions:
      - *check-config
      - *check-key

######## cleanup ########

  clean:
    desc: Remove all build artifacts
    cmds:
      - rm -rf out

  clean-keys:
    desc: Remove all keys
    cmds:
      - rm -rf out/keys

  clean-toolchain:
    desc: Remove all go tools
    deps:
      - go:clean

  clean-os:
    desc: Remove os-packages
    cmds:
      - rm -rf out/os-packages

  clean-all:
    desc: Remove all build artifacts, cache and config file
    deps: [clean]
    cmds:
      - rm -rf cache
      - rm -rf .task
      - rm -f .config
