version: '3'

vars:
  # Config file
  CONFIG: st.config
  # Build Targets
  ISO: out/stboot.iso
  PROVISO: out/prov.iso
  # Build Artifacts
  STBOOT_LINUX_IMAGE: out/artifacts/stboot.vmlinuz
  STBOOT_INITRAMFS: out/artifacts/stboot.cpio.gz
  TRUST_POLICY: out/artifacts/trust_policy.json
  HOST_CONFIG: contrib/example_host_configuration.json
  # task helper script
  CONFIG_HELPER: "CONFIG={{.CONFIG}} ./.task_config.sh"


dotenv:
  - "{{.CONFIG}}"

includes:
  demo: ./tasks/demo.yml
  deps: ./tasks/deps.yml
  go: ./tasks/go.yml
  linux: ./tasks/linux.yml
  stboot: ./tasks/stboot.yml
  qemu: ./tasks/qemu.yml
  proviso: ./tasks/provision.yml

output: 'prefixed'

tasks:

  default:
    cmds:
      - task -l
    interactive: true

  fetch:
    desc: Fetch dependencies which require network access
    deps:
      - check-config
      - go:all
      - linux:fetch

  config:
    desc: Generate default configuration
    sources:
      - "{{.DEFAULT_CONFIG}}"
    generates:
      - "{{.CONFIG}}"
    cmds:
      - cmd: >-
             if [ -f {{.CONFIG}} ]; then
             echo Moving old config to {{.CONFIG}}.old;
             mv {{.CONFIG}} {{.CONFIG}}.old;
             fi
        silent: true
      - cp {{.DEFAULT_CONFIG}} {{.CONFIG}}
    vars:
      DEFAULT_CONFIG: contrib/default.config

  toolchain:
    desc: Build toolchain
    deps:
      - go:update

  iso:
    desc: Build stboot iso image
    deps:
      - check-config
      - task: linux:kernel
        vars:
          IMAGE: "{{.STBOOT_LINUX_IMAGE}}"
      - task: stboot:initramfs-standard
    sources:
      - "{{.STBOOT_LINUX_IMAGE}}"
      - "{{.STBOOT_INITRAMFS}}"
    generates:
      - "{{.ISO}}"
    cmds:
      - "{{.GOBIN}}/stmgr uki create -format iso -out '{{.ISO}}' -kernel={{.STBOOT_LINUX_IMAGE}} -initramfs={{.STBOOT_INITRAMFS}} -config='{{.HOST_CONFIG}}'"
    run: once

  iso-ospkg:
    desc: Build stboot iso image including an OS package inside the initramfs
    deps:
      - check-config
      - task: linux:kernel
        vars:
          IMAGE: "{{.STBOOT_LINUX_IMAGE}}"
      - task: stboot:initramfs-incl-ospkg
    sources:
      - "{{.STBOOT_LINUX_IMAGE}}"
      - "{{.STBOOT_INITRAMFS}}"
    generates:
      - "{{.ISO}}"
    cmds:
      - "{{.GOBIN}}/stmgr uki create -format iso -out '{{.ISO}}' -kernel={{.STBOOT_LINUX_IMAGE}} -initramfs={{.STBOOT_INITRAMFS}} -config='{{.HOST_CONFIG}}'"
    run: once


  trustpolicy:
    internal: yes
    deps:
      - task: go:stmgr
    generates:
      - "{{.TRUST_POLICY}}"
    cmds:
      - cmd: mkdir -p $(dirname {{.TRUST_POLICY}})
        silent: true
      - cmd: |-
          {{.GOBIN}}/stmgr trustpolicy check '{{.JSON}}' > {{.TRUST_POLICY}}
    vars:
      JSON: "{{.JSON}}"

  trustpolicy-network:
    desc: Generate trust_policy.json with arbitray data but ospkg_fetch_method set to "network"
    cmds:
      - task: trustpolicy
        vars:
          JSON: |-
            { 
              "ospkg_signature_threshold": 2,
              "ospkg_fetch_method": "network"
            }

  trustpolicy-initramfs:
    desc: Generate trust_policy.json with arbitray data but ospkg_fetch_method set to "initramfs"
    cmds:
      - task: trustpolicy
        vars:
          JSON: |-
            { 
              "ospkg_signature_threshold": 2,
              "ospkg_fetch_method": "initramfs"
            }


######## checks ########

  # TODO: add config file validation
  check-config:
    preconditions:
      - sh: '[ -f "{{.CONFIG}}" ]'
        msg: |-
          [ERROR] File "{{.CONFIG}}" missing
          Please provide a configuration file or run "task config"
    run: once

######## cleanup ########

  clean:
    desc: Remove all build artifacts
    cmds:
      - "rm -rf out"

  clean-toolchain:
    desc: Remove all go tools
    deps:
      - go:clean

  clean-all:
    desc: Remove all build artifacts, cache and config file
    deps:
      - clean
      - go:clean
    cmds:
      - "rm -rf cache"
      - "rm -rf .task"
      - "rm -f {{.CONFIG}}"


######## somehow outdated, maybe remove it ########
# it builds the stmgr provision hostconfig tool into
# an own iso/initramfs. This GUI tool was never actually used.
# It prompts for hostconfig input and writes it to qemu efivar.

  proviso:
    desc: Build provisioning iso image
    deps:
      - check-config
      - task: linux:kernel
        vars:
          IMAGE: "{{.PROVISIONING_LINUX_IMAGE}}"
      - task: proviso:provisioning-initramfs
    sources:
      - ./{{.PROVISIONING_LINUX_IMAGE}}
      - ./{{.PROVISIONING_INITRAMFS}}
    generates:
      - ./{{.PROVISO}}
    cmds:
      - "{{.GOBIN}}/stmgr uki create -format iso -out '{{.ISO}}' -kernel={{.PROVISIONING_LINUX_IMAGE}} -initramfs={{.PROVISIONING_INITRAMFS}}"
    vars:
      ISO_DIR: cache/proviso
      PROVISO_FAT: ./{{.ISO_DIR}}/provision.fat
      # TODO: Calculate size
      BLOCKS:
        sh: echo $((1<<16))
