version: '3'

vars:
  # override go environment
  # TODO: search an elegant solution
  go_env: 'GO111MODULE="off" GOPATH="${PWD}/cache/go"'

dotenv:
  - .config

includes:
  go: ./go.yml
  deps: ./deps.yml

output: 'prefixed'

tasks:

  default:
    deps: [image]

  config:
    desc: Generate default configuration
    cmds:
      - "./scripts/config.sh -o .config"
    sources:
      - contrib/default.config
    generates:
      - .config

  # XXX: Does not update toolchain binary!
  # TODO: Force toolchain rebuild for this target only
  # current workaround: task clean-toolchain toolchain
  toolchain:
    desc: Build toolchain
    deps:
      - go:all

######## stboot-installation ########

  image:
    desc: Build target installation option
    # TODO: make target installation option optional
    deps: [image-mbr]

  image-mbr:
    desc: Build MBR bootloader installation option
    deps:
      - mbr_boot_partition
      - data_partition
    cmds:
      - './stboot-installation/mbr-bootloader/build_image.sh >/dev/null'
    sources:
      - out/stboot-installation/data_partition.ext4
      - out/stboot-installation/mbr-bootloader/boot_partition.vfat
    generates:
      - out/stboot-installation/mbr-bootloader/stboot_mbr_installation.img
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""

  image-efi:
    desc: Build EFI application installation option
    deps:
      - efi_boot_partition
      - data_partition
    cmds:
      - './stboot-installation/efi-application/build_image.sh >/dev/null'
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""

  mbr_boot_partition:
    deps:
      - kernel
      - host_config
      - syslinux
      - syslinux_config
    cmds:
      - './stboot-installation/mbr-bootloader/build_boot_filesystem.sh >/dev/null'
    sources:
      - out/stboot-installation/initramfs-linuxboot.cpio.gz
      - out/stboot-installation/host_configuration.json
      - cache/syslinux/syslinux-6.03/bios/mtools/syslinux
      - out/stboot-installation/mbr-bootloader/syslinux.cfg
    generates:
      - out/stboot-installation/mbr-bootloader/boot_partition.vfat
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""

  data_partition:
    cmds:
      - './stboot-installation/common/build_data_filesystem.sh >/dev/null'
    sources:
      - out/os-packages
    generates:
      - out/stboot-installation/data_partition.ext4
    status:
      - './.task_config.sh data_partition stboot-installation/common/build_data_filesystem.sh'
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""

  host_config:
    cmds:
      - './stboot-installation/common/build_host_config.sh >/dev/null'
    generates:
      - out/stboot-installation/host_configuration.json
    status:
      - './.task_config.sh host_config stboot-installation/common/build_host_config.sh'
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""

  security_config:
    cmds:
      - './stboot-installation/common/build_security_config.sh >/dev/null'
    generates:
      - out/stboot-installation/security_configuration.json
    status:
      - './.task_config.sh security_config stboot-installation/common/build_security_config.sh'
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""

  syslinux:
    cmds:
      - './stboot-installation/mbr-bootloader/fetch_syslinux.sh >/dev/null'
        # TODO: integrate into the the script above
      - 'cp cache/syslinux/syslinux-6.03/efi32/efi/syslinux.efi out/stboot-installation/mbr-bootloader/BOOTIA32.EFI'
      - 'cp cache/syslinux/syslinux-6.03/efi64/efi/syslinux.efi out/stboot-installation/mbr-bootloader/BOOTX64.EFI'
    generates:
      - cache/syslinux/syslinux-6.03/bios/mtools/syslinux
    status:
      - 'test -x cache/syslinux/syslinux-6.03/bios/mtools/syslinux'

  syslinux_config:
    cmds:
      - './stboot-installation/mbr-bootloader/build_syslinux_config.sh >/dev/null'
    generates:
      - out/stboot-installation/mbr-bootloader/syslinux.cfg
    status:
      - 'test -f out/stboot-installation/mbr-bootloader/syslinux.cfg'

######## keygen ########

  keygen:
    desc: Generate all example keys
    deps:
      - keygen-sign
      - keygen-cpu

  keygen-sign:
    desc: Generate example sign keys
    deps:
      - go:stmanager
    cmds:
      - './scripts/make_signing_keys.sh -o out/keys/signing_keys/ >/dev/null'
    generates:
      - out/keys/signing_keys/*

  keygen-cpu:
    desc: Generate cpu ssh keys for debugging
    cmds:
      - './scripts/make_cpu_keys.sh -o out/keys/cpu_keys/ >/dev/null'
    generates:
      - out/keys/cpu_keys/*
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""

######## LinuxBoot kernel ########

  kernel:
    desc: Build LinuxBoot kernel
    deps:
      - initramfs
    cmds:
      - 'make -f modules/linux.mk OUT=out/stboot-installation CACHE=cache'
    status:
      - './.task_config.sh kernel modules/linux.mk'
    sources:
      - out/stboot-installation/initramfs-linuxboot.cpio.gz
    generates:
      - out/stboot-installation/linuxboot.vmlinuz
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""

  initramfs:
    deps:
      - go:u-root
      - security_config
    sources:
      - out/stboot-installation/security_configuration.json
    generates:
      - out/stboot-installation/initramfs-linuxboot.cpio.gz
    cmds:
      - './stboot-installation/common/build_initramfs.sh >/dev/null'
    preconditions:
      - sh: test -f .config
        msg: "Configuration (.config) file missing\nPlease provide a config file or run \"task config\""
      - sh: test -f {{.ST_SIGNING_ROOT}}
        msg: "root certificate ({{.ST_SIGNING_ROOT}}) missing\nPlease provide a certificate or run \"task keygen-sign\""

######## cleanup ########

  clean:
    desc: Remove all build artifacts
    cmds:
      - rm -rf out

  clean-keys:
    desc: Remove all keys
    cmds:
      - rm -rf out/keys

  clean-toolchain:
    desc: Remove all go tools
    deps:
      - go:clean

  clean-os:
    desc: Remove os-packages
    cmds:
      - rm -rf out/os-packages

  clean-all:
    desc: Remove all build artifacts, cache and config file
    deps: [clean]
    cmds:
      - rm -rf cache
      - rm -rf .task
      - rm -f .config
