version: '3'

preconditions:
  <<: &check-config
    sh: test -f "{{.CONFIG}}"
    msg: "Configuration ({{.CONFIG}}) file missing\nPlease provide a config file or run \"task config\""

tasks:
  keygen:
    desc: Generate example sign keys
    deps:
      - :go:stmanager
    generates:
      - "{{.SIGNKEYS_DIR}}/*"
    cmds:
      - "{{.KEYGEN_SIGN_SCRIPT}} -o {{.SIGNKEYS_DIR}}"
    status:
      - "{{.CONFIG_HELPER}} keygen-sign {{.KEYGEN_SIGN_SCRIPT}}"
      - "test -d {{.SIGNKEYS_DIR}}"
      - "for i in {1..{{.ST_NUM_SIGNATURES}}}; do [[ -f {{.KEYS_DIR}}/signing-key-$i.key ]] || exit 1; done"
      - "for i in {1..{{.ST_NUM_SIGNATURES}}}; do [[ -f {{.KEYS_DIR}}/signing-key-$i.cert ]] || exit 1; done"
    preconditions:
      - *check-config
    vars:
      KEYGEN_SIGN_SCRIPT: ./scripts/signing_keys.sh
      SIGNKEYS_DIR: out/keys/signing_keys/

  ospkg:
    desc: "Build demo os package"
    deps:
      - :go:stmanager
      - ubuntu
    cmds:
      - "mkdir -p {{.ST_LOCAL_OSPKG_DIR}}"
      - "stmanager create --out '{{.ST_LOCAL_OSPKG_DIR}}/{{.EXAMPLE_OSPKG}}' --label='{{.LABEL}}' --kernel={{.KERNEL}} --initramfs={{.INITRD}} --cmd='{{.CMDLINE}}'"
      - "for i in {1..{{.ST_NUM_SIGNATURES}}}; do stmanager sign --key={{.KEYS_DIR}}/signing-key-$i.key --cert={{.KEYS_DIR}}/signing-key-$i.cert {{.ST_LOCAL_OSPKG_DIR}}/{{.EXAMPLE_OSPKG}}; done"
      - "echo {{.EXAMPLE_OSPKG}} > {{.ST_LOCAL_OSPKG_DIR}}/boot_order"
    status:
      - "test -f {{.ST_LOCAL_OSPKG_DIR}}/{{.EXAMPLE_OSPKG}}"
      - "test -f {{.ST_LOCAL_OSPKG_DIR}}/boot_order"
    preconditions:
      - *check-config
      - sh: '[[ -f /etc/os-release ]] && sed -n "s/^ID.*=\(.*\)$/\1/p" /etc/os-release|grep -q debian'
        msg: "OS is not debian based"
      - sh: '! (find {{.ST_LOCAL_OSPKG_DIR}} -name \*.zip | grep -v {{.EXAMPLE_OSPKG}} | read)'
        msg: "Path \"{{.ST_LOCAL_OSPKG_DIR}}\" already contain OS packages. Remove them to create an example OS Package"
      - sh: "for i in {1..{{.ST_NUM_SIGNATURES}}}; do [[ -f {{.KEYS_DIR}}/signing-key-$i.key ]] || exit 1; done"
        msg: "Missing sign key. Run \"task demo:keygen\" to generate examples keys and certificates"
      - sh: "for i in {1..{{.ST_NUM_SIGNATURES}}}; do [[ -f {{.KEYS_DIR}}/signing-key-$i.cert ]] || exit 1; done"
        msg: "Missing sign certificate. Run \"task demo:keygen\" to generate examples keys and certificates"
    vars:
      KEYS_DIR:
        sh: "dirname {{.ST_SIGNING_ROOT}} 2>/dev/null || echo ."
      EXAMPLE_OSPKG: "os-pkg-example-ubuntu20.zip"
      LABEL: System Transparency Test OS
      KERNEL: out/example-os/ubuntu-focal-amd64.vmlinuz
      INITRD: out/example-os/ubuntu-focal-amd64.cpio.gz
      CMDLINE: console=tty0 console=ttyS0,115200n8 rw rdinit=/lib/systemd/systemd

  ubuntu:
    deps:
      - :go:debos
    cmds:
      - "mkdir -p out/example-os"
      - "debos --artifactdir=out/example-os --template-var=suite:focal contrib/debos/ubuntu.yaml"
    status:
      - "test -f {{.KERNEL}}"
      - "test -f {{.INITRD}}"
    vars:
      KERNEL: out/example-os/ubuntu-focal-amd64.vmlinuz
      INITRD: out/example-os/ubuntu-focal-amd64.cpio.gz
