version: '3'

vars:
  INITRAMFS_INCLUDE: contrib/initramfs-includes
  PROVISIONING_INITRC: out/artifacts/proviso.elv
  STBOOT_ARGS: -loglevel=d

tasks:
  
  u-root:
    internal: yes
    deps:
      - :hostconfig
      - :go:u-root
      - :go:checkout-uroot
      - :go:checkout-stboot
    sources:
      - "{{.TRUST_POLICY}}"
      - "{{.HOST_CONFIG}}"
      - "{{.SIGNING_ROOT}}"
      - "{{.HTTPS_ROOT}}"
      - "cache/go/src/{{.UROOT_REPO}}/**"
      - "cache/go/src/{{.STBOOT_REPO}}/**"
    generates:
      - "{{.OUTPUT}}"
    method: timestamp
    cmds:
      - cmd: echo "Building initramfs via u-root with stboot as init process"
        silent: yes
      - cmd: echo "Including files:"
        silent: yes
      - cmd: for f in {{.FILES}}; do echo "- $f" ; done
        silent: yes
      - >
        {{.GOPREFIX}} {{.GOBIN}}/u-root -build=bb -uinitcmd="stboot {{.STBOOT_ARGS}}" -defaultsh=""
        -uroot-source ./cache/go/src/{{.UROOT_REPO}}
        -o {{.OUTPUT}}.tmp {{.FILES_ARGS}} {{.PKGS_ARGS}}
      - mv {{.OUTPUT}}.tmp {{.OUTPUT}}
    env:
      GO111MODULE: off
    preconditions:
      - sh: "[ -n \"{{.OUTPUT}}\" ]"
        msg: "task bug: OUTPUT not defined"
      - sh: "[ -e \"{{.SIGNING_ROOT}}\" ]"
        msg: |-
          [ERROR] root certificate ({{.SIGNING_ROOT}}) missing.
          Please provide a certificate or run "task demo:keygen" to generate example keys.
    status:
      - "[ -f {{.STBOOT_INITRAMFS}} ]"
    run: when_changed
    vars:
      HTTPS_ROOT: contrib/initramfs-includes/isrgrootx1.pem
      SIGNING_ROOT: out/keys/example_keys/root.cert
      FILES: >-
        {{.HOST_CONFIG}}:etc/host_configuration.json
        {{.TRUST_POLICY}}:etc/trust_policy/trust_policy.json
        {{.SIGNING_ROOT}}:etc/trust_policy/ospkg_signing_root.pem
        {{.HTTPS_ROOT}}:etc/ssl/certs/isrgrootx1.pem
        {{.FILES}}
      FILES_ARGS:
        sh: for f in {{.FILES}}; do echo -n "-files $f "; done
      PKGS_ARGS: >-
        {{.UROOT_REPO}}/cmds/core/init
        {{.STBOOT_REPO}}
        {{.UROOT_PKGS}}
      OUTPUT: "{{.OUTPUT}}"

  initramfs:
    internal: yes
    deps:
      - task: u-root
        vars:
          OUTPUT: "{{.VARIANT_SRC}}"
          FILES: "{{.FILES}}"
    sources:
      - "{{.VARIANT_SRC}}"
    generates:
      - "{{.STBOOT_INITRAMFS}}"
    method: timestamp
    cmds:
      - gzip -kf {{.VARIANT_SRC}}
      - mv {{.VARIANT_SRC}}.gz {{.STBOOT_INITRAMFS}}
    status:
      - '[ -f "{{.STBOOT_INITRAMFS}}" ]'
    run: once
    vars:
      VARIANT: "{{.VARIANT}}"
      VARIANT_SRC: out/artifacts/{{.VARIANT}}.cpio
      FILES: "{{.FILES}}"

  initramfs-standard:
    desc: "Build an initramfs with stboot as init process"
    deps:
      - :trustpolicy-network
    cmds:
      - task: initramfs
        vars:
          VARIANT: initramfs-standard
    run: once

  initramfs-incl-ospkg:
    desc: "Build an initramfs with stboot as init process including an OS package"
    deps:
      - :trustpolicy-initramfs
    cmds:
      - task: initramfs
        vars:
          VARIANT: initramfs-incl-ospkg
          FILES: >-
            "{{.OSPKGARCHIVE}}":ospkg/ospkg.json
            "{{.OSPKGDESCRIPTOR}}":ospkg/ospkg.zip
    preconditions:
      - sh: >-
          [ -f "{{.OSPKGARCHIVE}}" ] && [ -f "{{.OSPKGDESCRIPTOR}}" ]
        msg: |-
          [ERROR] Missing OS package artifacts ({{.OSPKGARCHIVE}} and {{.OSPKGDESCRIPTOR}}). Either provide them manually or try running 'task demo:ospkg'
    run: once
    vars:
      OSPKGARCHIVE: "{{.OSPKG_DIR}}/os-pkg-example-ubuntu20.json"
      OSPKGDESCRIPTOR: "{{.OSPKG_DIR}}/os-pkg-example-ubuntu20.zip"

# TODO:
# To cover both paths of hostconfig autodetect:
#
# - make a `initramfs-incl-host-config` including
#   {{.HOST_CONFIG}}:etc/host_configuration.json
#
# - write something in qemu: to preset the OVMF_VARS.fd with host config
